### ISSUE TITLE
2008 map is gone

### ISSUE THREAD

**Issue by westnordost** [mvexel/thenandnow#11]
For the 2008 map, I get "502 Bad Gateway" for the tiles on the 2008 map.

On e.g. https://mvexel.github.io/thenandnow/#13/1.3226/103.8497

**Comment by mvexel** [comment]
Oops, yes, I need to reboot some things. I really need a trigger to notify me when this thing goes down.. (Ideas welcome)

**Comment by mvexel** [comment]
OK works again!

**Comment by westnordost** [comment]
What is most feasible depends on your setup I guess. You could set up a cron job that tries to access a random tile and if it returns anything other than 200 OK, send an email about the error to your email address.

If you rent a webspace, you usually have an option somewhere in the admin interface to let it schedule periodic executions of a cgi-script that's somewhere on that webspace. E.g. I use a webspace that has Plesk Obsidian as a management interface installed and I can add any PHP (and other) scripts to be executed in intervals. If an execution fails (e.g. due to a 502 Bad Gateway response), I will automatically get a notification about that it failed. (See [Plesk docs](https://docs.plesk.com/en-US/obsidian/customer-guide/scheduling-tasks.65207/), other webspace management interfaces surely have something similar )

I use this mechanism to pull updates from the improveOSM oneway-data daily ([this script](https://github.com/streetcomplete/oneway-data-api/blob/master/update.php#L63))

**Comment by mvexel** [comment]
thanks for the help @westnordost !
