### ISSUE TITLE
Add 2006 tiles

### ISSUE THREAD

**Issue by tuxayo** [mvexel/thenandnow#4]
Someone provides 2006 tiles, what do you think about allowing to swap from 2007 to 2006 and other years if someone makes them available?
http://osmz.ru/osm2006.html#8/51.281/0.459

**Comment by lucadelu** [comment]
@mvexel I think could be more useful have several years in the same website, for example in 2007 Italy  is more or less empty. Could you be interested to add more sources if someone provide them?

**Comment by mvexel** [comment]
If someone provides a tile layer I can just add by pointing to it, I will add it to this site.

**Comment by mvexel** [comment]
No other tile sets seem to be available. The 2006 tiles mentioned above do not load. If someone wants to fork and build out with other tiles, feel free to do so, but it's out of scope for this simple project. Have fun and I'm looking forward to seeing what you all come up with!
