### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by rugk** [mvexel/thenandnow#8]
Currently when accessed via HTTPS, we get mixed content warnings as the tiles are downloaded over HTTP.

We do not want that.

Related: https://github.com/openstreetmap/operations/issues/117

**Comment by mvexel** [comment]
How do you suggest this be fixed?

**Comment by rugk** [comment]
Good question. `tile.rtijn.org` does not seem to support HTTPS, so maybe choose on, which does?

**Comment by mvexel** [comment]
I don't have another server to run this on, unfortunately :( I can look into getting an SSL certificate for that server, but since I've never configured a web server for https before, it will take me some time to figure that out. Unless you're offering help :)

**Comment by rugk** [comment]
With [Let's Encrypt](https://letsencrypt.org/) it's easy. So [here you go](https://certbot.eff.org/), it takes 5 minutes, [no really](https://www.youtube.com/watch?v=k0g21V4MPns).

**Comment by tyrasd** [comment]
I guess this is now obsolete after 95b6852d48be8fcbd8eec74b7718610bbb058359, isn't it?

**Comment by rugk** [comment]
Oh, this is sad to see…

However, in some way we can even say it's fixed, because https://mvexel.github.io/thenandnow/ is a HTTPS-website.

**Comment by rugk** [comment]
Anyway, I just visited it and https://tile.rtijn.org now works and uses a Let'S Encrypt certificate. So this issue is actually solved… :upside_down_face:
